#!/usr/bin/env python3

print('int64 z')
print('int64 h')
print('int64 m')
print('int64 grs')
print('int64 fuv')
print('int64 oldg')
print('int64 mnew')
print('int64 loop')
print('')
print('enter innerloop')
print('')
print('loop = 20000')
print('')
print('innerloop:')
print('')

print('fuv = 0')
print('grs = 0')
print('m = 0')

for loop in range(50):
  print('  z = 0')
  print('  oldg = grs')
  print('  h = grs + fuv')
  print('              =? grs & 1')
  print('')
  print('  z = m   if !=')
  print('  h = grs if  =')
  print('  mnew = m - 1')
  print('  grs -= fuv')
  print('')
  print('  (int64) grs >>= 1')
  print('  (int64) h >>= 1')
  print('  m = ~m')
  print('                 signed<? z - 0')
  print('')
  print('  fuv = oldg if  signed<')
  print('  grs = h    if !signed<')
  print('  m = mnew   if !signed<')
  print('')

print('=? loop -= 1')
print('goto innerloop if !=')
print('')
print('return')
